### ISSUE TITLE
关于字体颜色的显示

### ISSUE THREAD

**Issue by 01WarpDrive** [Chilly-Blaze/MastersTasks#1]
任务默认的color参数为0，即字符串中的\033[30，在终端中显示为黑色。
对我这类黑色背景终端的用户不友好。当然这是个小细节，修改起来很方便。

我最近正好想构建一个自己的任务管理程序，
您的代码和思路给了我不少启发，支持。

**Comment by Chilly-Blaze** [comment]
> 任务默认的color参数为0，即字符串中的\033[30，在终端中显示为黑色。 对我这类黑色背景终端的用户不友好。当然这是个小细节，修改起来很方便。
> 
> 我最近正好想构建一个自己的任务管理程序， 您的代码和思路给了我不少启发，支持。

十分感谢你的建议，这个项目当初只是刚学python和git的时候练手用的，之后为了应付课设进行了重写甚至没有时间改写README，以为没人看就作为自用搁置了，代码实现也没什么难度，你能发现它着实令我受宠若惊，再次感谢你的支持❤️

**Comment by Chilly-Blaze** [comment]
> 任务默认的color参数为0，即字符串中的\033[30，在终端中显示为黑色。 对我这类黑色背景终端的用户不友好。当然这是个小细节，修改起来很方便。
> 
> 我最近正好想构建一个自己的任务管理程序， 您的代码和思路给了我不少启发，支持。

已修复
